name: 'dbt_cloud_demo'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]

models:
  dbt_cloud_demo:
    example:
      +materialized: table
    ORDERS:
      +materialized: table
