
version: 2

models:
    - name: orders
      description: "A starter dbt model"
      config:
              enabled: true
      columns:
          - name: order_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
